; ===================================================================

[External compressor:precomp]
header    = 0
unpackcmd = "Precomp\precomp.exe" -o$$arcdatafile$$.tmp -r $$arcpackedfile$$.tmp

; ===================================================================

[External compressor:afr,afr_020]
header    = 0
unpackcmd = "AFR\AFR.exe" d #in #out <stdin> <stdout>

; ===================================================================

[External compressor:xt_zlib,xt_lz4,xt_lzo,xt_zstd,xt_oodle]
header    = 0
unpackcmd = "XTool\XTool.exe" d:precomp:t90p - - <stdin> <stdout>

[External compressor:xt_crilayla]
header    = 0
unpackcmd = "CriLayla\XTool.exe" d:precomp:t50p - - <stdin> <stdout>

; ===================================================================

[External compressor:xtool,xtool_plugin]
header    = 0
unpackcmd = "XTool_2020\{compressor}.exe" decode -t100p - - <stdin> <stdout>

; ===================================================================

[External compressor:oo2reck,oo2recm,oo2recs]
header    = 0
unpackcmd = "OodleRec\{compressor}\{compressor}.exe" d <stdin> <stdout>

[External compressor:zstdrec]
header    = 0
unpackcmd = "ZSTDRec\zstdrec.exe" d <stdin> <stdout>

[External compressor:lzorec]
header    = 0
unpackcmd = "LZORec\lzorec.exe" d <stdin> <stdout>

[External compressor:lzxrec]
header    = 0
packcmd   = "LZXRec\lzxrec.exe" e <stdin> <stdout>

;Cyberpunk 2077
[External compressor:cp_2077]
header    = 0
unpackcmd = "Cyberpunk2077\XTool_CP2077.exe" decode -t100p - - <stdin> <stdout>

; Metro Exodus
[External compressor:vfxrec]
header    = 0
unpackcmd = "MetroExodus\vfxrec.exe" d <stdin> <stdout>

;FIFA 19
[External compressor:fifa19_oo2reck]
header    = 0
unpackcmd = "FIFA19\fifa19_oo2reck.exe" d <stdin> <stdout>

[External compressor:cdt]
header    = 0
unpackcmd = "FIFA19\cdt.exe" <stdin> <stdout>

;Project CARS 2
[External compressor:pcars2_oo2reck]
header    = 0
unpackcmd = "ProjectCars2\oo2reck.exe" d <stdin> <stdout>

[External compressor:pcars2_bdt]
header    = 0
unpackcmd = "ProjectCars2\bdt.exe" r <stdin> <stdout>

;Project CARS 3
[External compressor:pcars3_oo2reck]
header    = 0
unpackcmd = "ProjectCars3\oo2reck.exe" d <stdin> <stdout>

[External compressor:pcars3_bdt]
header    = 0
unpackcmd = "ProjectCars3\bdt.exe" r <stdin> <stdout>

;Saints Row 3R
[External compressor:vpprec]
header    = 0
unpackcmd = "SR3Remaster\vpprec.exe" d <stdin> <stdout>

;Death Stranding
[External compressor:dst_oo2reck]
header    = 0
unpackcmd = "DStranding\oo2reck.exe" d <stdin> <stdout>

[External compressor:dst]
header    = 0
unpackcmd = "DStranding\dstool.exe" <stdin> <stdout>

;Unreal Engine 4 Decryption Tool
[External compressor:ue4dt]
header    = 0
unpackcmd = "UE4DT\ue4dt.exe" d {options} <stdin> <stdout>

;The Elder Scrolls V: Skyrim
[External compressor:xtool_skyrim]
header    = 0
unpackcmd = "XToolSkyrim\XTool.exe" decode -t100p - - <stdin> <stdout>

; ===================================================================

[External compressor:brunsli]
header     = 0
unpackcmd  = "BRUNSLI\brunsli.exe" d $$arcdatafile$$.brn $$arcdatafile$$.jpg
datafile   = $$arcdatafile$$.jpg
packedfile = $$arcdatafile$$.brn
solid      = 0

[External compressor:packjpg]
header     = 0
unpackcmd  = "JPG\packjpg.exe" -np {options} $$arcdatafile$$.pjg
datafile   = $$arcdatafile$$.jpg
packedfile = $$arcdatafile$$.pjg
solid      = 0

[External compressor:packmp3]
header     = 0
unpackcmd  = "MP3\packmp3.exe" -np {options} $$arcdatafile$$.pmp
datafile   = $$arcdatafile$$.mp3
packedfile = $$arcdatafile$$.pmp
solid      = 0

[External compressor:mpz,mpzapi]
header    = 0
unpackcmd = "MPZ\mpzapi.exe" d <stdin> <stdout>

; ===================================================================

[External compressor:lzma_sdk]
header    = 0
unpackcmd = "7ZIP\lzma_sdk.exe" d -si -so <stdin> <stdout>

[External compressor:lzma2,7z]
header    = 0
unpackcmd = "7ZIP\7z.exe" x -txz -an -y -si -so <stdin> <stdout>

[External compressor:rar]
dmem       = 200
unpackcmd  = "RAR\UnRAR.exe" e -mt4 $$arcpackedfile$$.tmp.rar
datafile   = $$arcdatafile$$.tmp
packedfile = $$arcpackedfile$$.tmp.rar

[External compressor:zstd]
header     = 0
unpackcmd  = "ZSTD\zstd.exe" -d {options} -f <stdin> <stdout>

; ===================================================================

[External compressor:rz,razor]
header    = 0
unpackcmd = "RAZOR\STANDARD\RZ.exe" e -y $$arcpackedfile$$.tmp $$arcdatafile$$.tmp

[External compressor:rz_stdio,razor_stdio]
header    = 0
unpackcmd = "RAZOR\STDIO\RAZOR.exe" e -y $stdio$ <stdin> <stdout>

; ===================================================================

[External compressor:mpz_pmt,mpzapi_pmt,precomp_pmt,razor_pmt,rz_pmt]
header    = 0
unpackcmd = "PMT\PMT.exe" d {compressor} -t100p - - <stdin> <stdout>

; ===================================================================

[External compressor:precomp_mtx]
header    = 0
default   = -t100p
unpackcmd = "MTX\MTX.exe" x -mprecomp {options} --basePath=".\..\" --cfgFile="$basePath$\Arc.ini" --tmpPath="$basePath$\TEMP" - - <stdin> <stdout>

[External compressor:mpz_mtx,mpzapi_mtx]
header    = 0
default   = -t100p
unpackcmd = "MTX\MTX.exe" x -mmpz {options} --basePath=".\..\" --cfgFile="$basePath$\Arc.ini" --tmpPath="$basePath$\TEMP" - - <stdin> <stdout>

[External compressor:rz_mtx,razor_mtx]
header    = 0
default   = -t100p
unpackcmd = "MTX\MTX.exe" x -mrz {options} --basePath=".\..\" --cfgFile="$basePath$\Arc.ini" --tmpPath="$basePath$\TEMP" - - <stdin> <stdout>

; ===================================================================
