[XTool_Bms2xtl_L1]
XTool_Bms2xtl_DB;   Type: RADIO; Text: Redout 2;                                                   Method: xtool;   Params: c32mb:mredout2;

;;---------------------------------------------------------------------------------------------------
[COPY.BEFORE]
Redout2.DB;             Method: xtool:mredout2:1;

[Copy.Redout2.DB]
ADDONS\Libraries\Oodle\oo2core_9_win64.dll;                Search: oo2core_9_win64.dll;       Destination: PRE\XTool_2020\oo2core_9_win64.dll;
PSC: Function.CREATE_DATABASE|redout2|*.pak|unreal_tournament_4_0.4.27c_paks_only|1erCkaJ5WigLfQ0t7Bq6iLw-g9enDNNTH|leviathan||0;

;;---------------------------------------------------------------------------------------------------
[DECOMPRESSORS]
Redout2;              Method: xtool:mredout2;

[Decomp.Redout2]
ADDONS\Libraries\Oodle\oo2core_9_win64.dll;                Search: oo2core_9_win64.dll;       Destination: XTool_2020\oo2core_9_win64.dll;

;;---------------------------------------------------------------------------------------------------
[DOWNLOAD]
12PE1rJCZmtvr8Ntlni-cdneS2h_Mn3eP|TOOLS\;  Method: xtool:mredout2:1;   Check: FileExists|TOOLS\Bms2XTool\bms2xtl.exe;  Description: QuickBMS to XTool;
