#!/usr/bin/env python3
"""Generate a PyInstaller Windows version-info resource from __version__.

Build_EXE.bat runs this before compiling; it reads the __version__ string out
of DMPRepackGUI.py (by regex, so importing the GUI is never triggered) and
writes version_info.txt, which PyInstaller stamps into the .exe's file
properties via --version-file.

Relative paths only, so it works from any checkout location / drive.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "DMPRepackGUI.py"
OUT = HERE / "version_info.txt"

src = SRC.read_text(encoding="utf-8")
m = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', src)
version = m.group(1) if m else "0.0.0"

# Windows FILEVERSION / PRODUCTVERSION want a 4-tuple of ints.
parts = [int(n) for n in re.findall(r"\d+", version)][:4]
parts += [0] * (4 - len(parts))
vtuple = ", ".join(str(p) for p in parts)

template = f"""# UTF-8
# Auto-generated by make_version_file.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({vtuple}),
    prodvers=({vtuple}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'ARMGDDN Games'),
        StringStruct('FileDescription', 'AG Repack GUI'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'AG Repack GUI'),
        StringStruct('LegalCopyright', 'DMP of ARMGDDN Games'),
        StringStruct('OriginalFilename', 'AG Repack GUI.exe'),
        StringStruct('ProductName', 'AG Repack GUI'),
        StringStruct('ProductVersion', '{version}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

OUT.write_text(template, encoding="utf-8")
print(f"version_info.txt written for v{version}  ({vtuple})")
