
#define NeedSize "15.000.000.000"

;#define Tasks
;#define Components
#define SecondProgressBar

;#define DSG_InternalDLL         /* Adding Setup.dll/<outputfiename>.dll next to the script will compress the DLL file into the Setup.exe/<outputfiename>.exe file  */
;#define DSG_PasswordDLL "123"   /* Same password used in DiskSpan_GUI to extract decompressors from Setup.dll files */

#define DSG_CreateUninstallList  /* Use file list generated by DiskSpan GUI to uninstall the application */

[Setup]
AppName=ISDone
AppVerName=ISDone
DefaultDirName={{#VER >= 0x06000000 ? "common" : void}pf}\ISDone
DefaultGroupName=ISDone Example
OutputDir=Output
OutputBaseFilename=Setup
SetupIconFile=Include\Setup.ico
VersionInfoCopyright=ProFrager
SolidCompression=yes
DisableWelcomePage=no
UsePreviousAppDir=no
DirExistsWarning=no
ShowLanguageDialog=yes
WizardImageFile=compiler:Wiz{#VER < 0x06020000 ? "Modern" : "Classic"}Image-IS.bmp
WizardSmallImageFile=compiler:Wiz{#VER < 0x06020000 ? "Modern" : "Classic"}SmallImage-IS.bmp
#ifdef NeedSize
ExtraDiskSpaceRequired={#StringChange(NeedSize, ".", "")}
#endif
;#define DEBUG

#ifdef Components
[Types]
Name: full; Description: Full installation; Flags: iscustom

[Components]
Name: comp1; Description: Game 1; Types: full; ExtraDiskSpaceRequired: 100000000
Name: comp2; Description: Game 2; Types: full; ExtraDiskSpaceRequired: 200000000
Name: comp3; Description: Russian; Types: full; ExtraDiskSpaceRequired: 200000000; Languages: russian;
#endif

[Registry]
Root: HKLM; Subkey: Software\ProFrager; ValueName: path; ValueType: String; ValueData: {app}; Flags: uninsdeletekey; Check: CheckError
Root: HKLM; Subkey: Software\ProFrager; ValueName: name; ValueType: String; ValueData: Data; Flags: uninsdeletekey; Check: CheckError

[Icons]
Name: "{group}\Удалить пример ISDone"; Filename: {app}\unins000.exe; WorkingDir: {app}; Check: CheckError
Name: "{commondesktop}\Удалить пример ISDone"; Filename: {app}\unins000.exe; WorkingDir: {app}; Check: CheckError

[Tasks]
Name: VCCheck; Description: Установить Microsoft Visual C++ 2005 Redist
Name: PhysXCheck; Description: Установить Nvidia PhysX
#ifdef Tasks
Name: task1; Description: Install *.ini files for Game 1;{#ifdef Components} Components: Comp1;{#endif}
Name: task2; Description: Install *.ini files for Game 2;{#ifdef Components} Components: Comp2;{#endif}
Name: task2\subitem; Description: Sub Item;{#ifdef Components} Components: Comp2;{#endif}
#endif

[Run]
Filename: "{src}\Redist\vcredist_x86.exe"; Parameters: /q; StatusMsg: Устанавливаем Microsoft Visual C++ 2005 Redist...; Flags: skipifdoesntexist; Tasks: VCCheck; Check: CheckError
Filename: "{src}\Redist\PhysX.exe"; Parameters: /qn; StatusMsg: Устанавливаем Nvidia PhysX...; Flags: skipifdoesntexist; Tasks: PhysXCheck; Check: CheckError

[CustomMessages]
english.StatusLabel=Unpacking archives...
english.CancelButton=Cancel unpacking
english.UnpackingError=Unpacking error!
english.ElapsedTime=Elapsed time: %1
english.RemainingTime=Remaining Time: %1
english.Extracting=Extracting %1...
english.MergingFile=Merging file %1 (%3%) to %2 (%4%)...
english.ChangeDiskLabel=Please insert disk %1 with %2 file.%nBrowse for required file?

russian.StatusLabel=Распаковка архивов...
russian.CancelButton=Отменить распаковку
russian.UnpackingError=Ошибка распаковки!
russian.ElapsedTime=Прошло: %1
russian.RemainingTime=Осталось времени: %1
russian.Extracting=Извлекается %1...
russian.MergingFile=Слияние файла %1 (%3%) с %2 (%4%)...
russian.ChangeDiskLabel=Пожалуйста, вставьте диск %1 с файлом %2 File.%nНайти нужный файл?

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl";
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl";

#include "Include\DSG_Module.iss"

[code]
const
  GWL_WNDPROC = (-4);
  GWL_HINSTANCE = (-6);
  GWL_HWNDPARENT = (-8);
  GWL_ID = (-12);
  GWL_STYLE = (-16);
  GWL_EXSTYLE = (-20);
  GWL_USERDATA = (-21);

  SS_LEFT           = 0;
  SS_CENTER         = 1;
  SS_RIGHT          = 2;
  SS_RIGHTJUST      = $400;
  SS_LEFTNOWORDWRAP = $00C;

var
  LabelOveralPct: TNewStaticText;
  LabelCurrFileName: TNewStaticText;
  LabelElapsedTime: TNewStaticText;
  LabelRemainingTime: TNewStaticText;
  ISDoneOveralProgressBar: TNewProgressBar;
  IsDoneCancelButton: TNewButton;
#ifdef SecondProgressBar
  LabelCurrentPct: TNewStaticText;
  ISDoneCurrentProgressBar: TNewProgressBar;
#endif

function GetWindowLong(hWnd: HWND; nIndex: Integer): Longint;
  external 'GetWindowLongW@user32.dll stdcall delayload';

function SetWindowLong(hWnd: HWND; nIndex: Integer; dwNewLong: Longint): Longint;
  external 'SetWindowLongW@user32.dll stdcall delayload';

procedure CancelButtonOnClick(Sender: TObject);
begin
  SuspendProc();
  if MsgBox(SetupMessage(msgExitSetupMessage), mbConfirmation, MB_YESNO) = IDYES then
    ISDoneCancel := 1;
  ResumeProc();
end;

procedure ISDone_HideControls();
begin
  WizardForm.FileNamelabel.Hide;
  ISDoneOveralProgressBar.Hide;
  LabelOveralPct.Hide;
  LabelCurrFileName.Hide;
  LabelElapsedTime.Hide;
  LabelRemainingTime.Hide;
  ISDoneCancelButton.Hide;
  #ifdef SecondProgressBar
  ISDoneCurrentProgressBar.Hide;
  LabelCurrentPct.Hide;
  #endif
end;

procedure ISDone_CreateControls();
var
  PBTop: Integer;
begin
  PBTop := ScaleY(50);
  ISDoneOveralProgressBar := TNewProgressBar.Create(WizardForm);
  with ISDoneOveralProgressBar do begin
    Parent   := WizardForm.InstallingPage;
    Left     := ScaleX(0);
    Top      := PBTop;
    Width    := WizardForm.ProgressGauge.Width - ScaleX(50);
    Height   := WizardForm.ProgressGauge.Height;
    Max      := 1000;
    Position := 0;
    #if VER >= 0x06000000
    Anchors := [akLeft, akTop, akRight];
    #endif
  end;
  LabelOveralPct := TNewStaticText.Create(WizardForm);
  with LabelOveralPct do begin
    Parent    := WizardForm.InstallingPage;
    AutoSize  := False;
    Caption   := '0.0%';
    Left      := ISDoneOveralProgressBar.Width + ScaleX(5);
    Top       := ISDoneOveralProgressBar.Top + ScaleY(3);
    Width     := ScaleX(40);
    SetWindowLong(Handle, GWL_STYLE, (GetWindowLong(Handle, GWL_STYLE) and (not SS_LEFT) and (not SS_CENTER) and (not SS_RIGHT) and (not SS_LEFTNOWORDWRAP)) or SS_CENTER);
    #if VER >= 0x06000000
    Anchors := [akTop, akRight];
    #endif
  end;
  LabelCurrFileName := TNewStaticText.Create(WizardForm);
  with LabelCurrFileName do begin
    Parent   := WizardForm.InstallingPage;
    AutoSize := False;
    Width    := ISDoneOveralProgressBar.Width + ScaleX(30);
    Left     := ScaleX(0);
    Top      := ScaleY(30);
    #if VER >= 0x06000000
    Anchors := WizardForm.FileNameLabel.Anchors;
    #endif
  end;
  #ifdef SecondProgressBar
  PBTop := PBTop + ScaleY(25);
  ISDoneCurrentProgressBar := TNewProgressBar.Create(WizardForm);
  with ISDoneCurrentProgressBar do begin
    Parent   := WizardForm.InstallingPage;
    Left     := ScaleX(0);
    Top      := PBTop + ScaleY(8);
    Width    := ISDoneOveralProgressBar.Width;
    Height   := WizardForm.ProgressGauge.Height;
    Max      := 1000;
    Position := 0;
    #if VER >= 0x06000000
    Anchors := [akLeft, akTop, akRight];
    #endif
  end;
  LabelCurrentPct := TNewStaticText.Create(WizardForm);
  with LabelCurrentPct do begin
    Parent    := WizardForm.InstallingPage;
    AutoSize  := False;
    Caption   := '0.0%';
    Left      := ISDoneCurrentProgressBar.Width + ScaleX(5);
    Top       := ISDoneCurrentProgressBar.Top + ScaleY(3);
    Width     := ScaleX(40);
    SetWindowLong(Handle, GWL_STYLE, (GetWindowLong(Handle, GWL_STYLE) and (not SS_LEFT) and (not SS_CENTER) and (not SS_RIGHT) and (not SS_LEFTNOWORDWRAP )) or SS_CENTER);
    #if VER >= 0x06000000
    Anchors := [akTop, akRight];
    #endif
  end;
  #endif
  LabelElapsedTime := TNewStaticText.Create(WizardForm);
  with LabelElapsedTime do begin
    Parent   := WizardForm.InstallingPage;
    AutoSize := False;
    Left     := ScaleX(0);
    Top      := PBTop + ScaleY(35);
    Width    := ISDoneOveralProgressBar.Width div 2;
    #if VER >= 0x06000000
    Anchors := [akLeft, akTop];
    #endif
  end;
  LabelRemainingTime := TNewStaticText.Create(WizardForm);
  with LabelRemainingTime do begin
    Parent   := WizardForm.InstallingPage;
    AutoSize := False;
    Left     := ISDoneOveralProgressBar.Width div 2;
    Top      := LabelElapsedTime.Top;
    Width    := LabelElapsedTime.Width + ScaleX(40);
    #if VER >= 0x06000000
    Anchors := [akLeft, akTop, akRight];
    #endif
  end;
  IsDoneCancelButton := TNewButton.Create(WizardForm);
  with IsDoneCancelButton do begin
    Parent   := WizardForm;
    Width    := ScaleX(135);
    Caption  := ExpandConstant('{cm:CancelButton}');
    Left     := WizardForm.CancelButton.Left + WizardForm.CancelButton.Width - ScaleX(135);
    Top      := WizardForm.CancelButton.Top;
    OnClick  := @CancelButtonOnClick;
    Enabled  := False;
    #if VER >= 0x06000000
    Anchors := [akTop, akRight];
    #endif
  end;
end;

// AFTER HERE IS REQUIRED TO WORK WITH DISKSPAN GUI
function MergeFileCallback(const State: TSplitState; const SrcFile, DstFile: WideString; SplitPos, MinProg, MaxProg: Integer; SrcPos, SrcSize, DstPos, DstSize: Extended): Boolean;
var
  Progress: Integer;
  SourcePct: Integer;
  DestinPct: Integer;
begin
  if State <> ssRead then
  begin
    SourcePct := Round(SrcPos * 1000 / DSG_MaxFloat(1, SrcSize));
    DestinPct := Round(DstPos * 1000 / DSG_MaxFloat(1, DstSize));
    Progress  := Round(SrcPos * MaxProg / DSG_MaxFloat(1, SrcSize * 1000)) + MinProg;
    LabelCurrFileName.Caption := FmtMessage(CustomMessage('MergingFile'), [ExtractFileName(SrcFile), ExtractFileName(DstFile),
      IntToStr(SourcePct div 10) + '.' + IntToStr(SourcePct mod 10), IntToStr(DestinPct div 10) + '.' + IntToStr(DestinPct mod 10)]);
    if Progress <= 1000 then
      ISDoneOveralProgressBar.Position := Progress;
    #ifdef SecondProgressBar
    if DestinPct <= 1000 then
      ISDoneCurrentProgressBar.Position := DestinPct;
    #endif
  end;
  Result := ISDoneCancel = 0;
end;

function ProgressCallback(OveralPct, CurrentPct: Integer; CurrentFile, TimeStr1, TimeStr2, TimeStr3: PAnsiChar): LongWord;
var
  NewWidth: Integer;
  Progress: Integer;
begin
  Progress := Round(SplitPct + Double(OveralPct));
  if Progress <= 1000 then
    ISDoneOveralProgressBar.Position := Progress;
  LabelOveralPct.Caption := IntToStr(Progress div 10) + '.' + Chr(48 + Progress mod 10) + '%';
  #ifdef SecondProgressBar
  if CurrentPct <= 1000 then
    ISDoneCurrentProgressBar.Position := CurrentPct;
  LabelCurrentPct.Caption := IntToStr(CurrentPct div 10) + '.' + Chr(48 + CurrentPct mod 10) + '%';
  #endif
  NewWidth := LabelCurrFileName.Width - DSG_GetTextWidth(CustomMessage('Extracting'), LabelCurrFileName.Font) + ScaleX(5)
  LabelCurrFileName.Caption := FmtMessage(CustomMessage('Extracting'), [MinimizePathName(
    DSG_IfThen(ArcSubDir = '', '', AddBackSlash('...\' + ArcSubDir)) + CurrentFile, LabelCurrFileName.Font, NewWidth)]);
  LabelElapsedTime.Caption := FmtMessage(CustomMessage('ElapsedTime'), [TimeStr2]);
  LabelRemainingTime.Caption := FmtMessage(CustomMessage('RemainingTime'), [TimeStr1]);
  Result := ISDoneCancel;
end;

procedure DiskSpanCallback(Status: TDiskSpanStatus);
begin
  case Status of
    cbStoped : begin
      ResumeProc();
      ISDoneCancel := 1;
      ISDoneError := True;
      WizardForm.NextButton.OnClick(WizardForm.NextButton);
    end;
    cbPaused  : SuspendProc();
    cbWorking : ResumeProc();
  end;
end;

procedure DSG_RefreshSelectedItems();
begin
  if not Assigned(DSG_LangList) then
  begin
    DSG_LangList := TStringList.Create;
  end;
  DSG_LangList.Clear;
  case LowerCase(ActiveLanguage) of
    'dutch'      : DSG_LangList.Append('NL');
    'english'    : DSG_LangList.Append('EN');
    'french'     : DSG_LangList.Append('FR');
    'german'     : DSG_LangList.Append('DE');
    'hungarian'  : DSG_LangList.Append('HU');
    'italian'    : DSG_LangList.Append('IT');
    'japanese'   : DSG_LangList.Append('JP');
    'portuguese' : DSG_LangList.Append('PTBR');
    'russian'    : DSG_LangList.Append('RU');
    'spanish'    : DSG_LangList.Append('ES');
  end;
  #ifdef DSG_Components
  if not Assigned(DSG_CompList) then
  begin
    DSG_CompList := TStringList.Create;
  end;
  DSG_CompList.Clear;
  if {#VER >= 0x06000000 ? "Wizard" : void}IsComponentSelected('comp1') then DSG_CompList.Append('1');
  if {#VER >= 0x06000000 ? "Wizard" : void}IsComponentSelected('comp2') then DSG_CompList.Append('2');
  if {#VER >= 0x06000000 ? "Wizard" : void}IsComponentSelected('comp3') then DSG_CompList.Append('3');
  #endif
  #ifdef DSG_Tasks
  if not Assigned(DSG_TaskList) then
  begin
    DSG_TaskList := TStringList.Create;
  end;
  DSG_TaskList.Clear;
  if {#VER >= 0x06000000 ? "Wizard" : void}IsTaskSelected('task1') then DSG_TaskList.Append('1');
  if {#VER >= 0x06000000 ? "Wizard" : void}IsTaskSelected('task2') then DSG_TaskList.Append('2');
  if {#VER >= 0x06000000 ? "Wizard" : void}IsTaskSelected('task2\subitem') then DSG_TaskList.Append('3');
  #endif
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpInstalling then
    DSG_RefreshSelectedItems();

  if (CurPageID = wpFinished) and ISDoneError then
  begin
    WizardForm.Caption := CustomMessage('UnpackingError');
    WizardForm.FinishedLabel.Font.Color := clRed;
    WizardForm.FinishedLabel.Caption := SetupMessage(msgSetupAborted);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then 
  begin
    WizardForm.ProgressGauge.Visible := False;;
    WizardForm.CancelButton.Visible := False;;
    ISDone_CreateControls();
    DSG_Unpack_Process(True, '', WizardForm.StatusLabel, LabelCurrFileName, ISDoneCancelButton, ISDoneOveralProgressBar, {#ifdef SecondProgressBar}ISDoneCurrentProgressBar{#else}nil{#endif}, @ProgressCallback, @MergeFileCallback, @DiskSpanCallback);
    // DSG_Unpack_Process(True, '', nil, nil, nil, nil, nil, nil, nil, nil); { no show progress }
    ISDone_HideControls();
    WizardForm.CancelButton.Visible := True;
    WizardForm.CancelButton.Enabled := False;
  end;
  if CurStep = ssPostInstall then
  begin
    #ifdef DSG_CreateUninstallList
    if (not ISDoneError) and FileCopy(ExpandConstant('{tmp}\Uninstall.dat'), ChangeFileExt(ExpandConstant('{uninstallexe}'), '.msg'), False) then
      DeleteFile(ExpandConstant('{tmp}\Uninstall.dat'));
    #endif
    if ISDoneError then
      ShellExec('open', ExpandConstant('{uninstallexe}'), '/VERYSILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

#ifdef DSG_CreateUninstallList
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin 
  if CurUninstallStep = usUninstall then
    DSG_CurUninstallStepChanged(CurUninstallStep, UninstallProgressForm.ProgressBar, nil);
  if CurUninstallStep = usPostUninstall then
    DSG_CurUninstallStepChanged(CurUninstallStep, nil, nil);
end;
#endif

#ifdef DEBUG
  #expr SaveToFile(AddBackslash(SourcePath) + "Script_PREPROCESSED.iss")
#endif