[InstallOptions]
GameSize=23.233.170.995
GameVersion=1.104.58.1030

;;--------------------------------------------------------------
[Task1]
Name=Expansion Packs
Size=0
ShowInstallLabel=0
Checked=1
Enabled=1
Level=0

[Task2]
;EP01
Name=Get To Work
Size=1.730.769.680
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task3]
;EP02
Name=Get Together
Size=1.767.282.579
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task4]
;EP03
Name=City Living
Size=2.663.204.649
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task5]
;EP04
Name=Cats && Dogs
Size=2.064.508.111
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task6]
;EP05
Name=Seasons
Size=1.435.353.381
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task7]
;EP06
Name=Get Famous
Size=2.838.774.859
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task8]
;EP07
Name=Island Living
Size=1.475.517.102
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task9]
;EP08
Name=Discovery University
Size=1.650.256.781
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task10]
;EP09
Name=Eco Lifestyle
Size=1.523.536.675
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task11]
;EP10
Name=Snowy Scape
Size=1.634.974.586
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task12]
;EP11
Name=Cottage Living
Size=1.720.068.232
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task13]
;EP12
Name=High School Years
Size=1.887.301.697
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task14]
;EP13
Name=Growing Together
Size=1.432.449.198
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task15]
;EP14
Name=Horse Ranch
Size=1.907.405.316
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task16]
;EP15
Name=For Rent
Size=1.569.254.935
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

;;--------------------------------------------------------------
[Task17]
Name=Free Packs
Size=0
ShowInstallLabel=0
Checked=1
Enabled=1
Level=0

[Task18]
;FP01
Name=Holiday Celebration Pack
Size=29.799.466
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

;;--------------------------------------------------------------
[Task19]
Name=Game Packs
Size=0
ShowInstallLabel=0
Checked=1
Enabled=1
Level=0

[Task20]
;GP01
Name=Outdoor Retreat
Size=704.672.072
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task21]
;GP02
Name=Spa Day
Size=537.540.205
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task22]
;GP03
Name=Dine Out
Size=475.501.328
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task23]
;GP04
Name=Vampires
Size=720.992.714
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task24]
;GP05
Name=Parenthood
Size=474.688.106
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task25]
;GP06
Name=Jungle Adventure
Size=958.799.474
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task26]
;GP07
Name=Strangerville
Size=712.545.941
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task27]
;GP08
Name=Realm of Magic
Size=933.284.178
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task28]
;GP09
Name=Star Wars - Journey to Batuu
Size=1.470.222.534
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task29]
;GP10
Name=Dream Home Decorator
Size=695.203.127
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task30]
;GP11
Name=My Wedding Stories
Size=955.608.175
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task31]
;GP12
Name=Werewolves
Size=987.851.727
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

;;--------------------------------------------------------------
[Task32]
Name=Stuff Packs
Size=0
ShowInstallLabel=0
Checked=1
Enabled=1
Level=0

[Task33]
;SP01
Name=Luxury Party
Size=120.717.606
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task34]
;SP02
Name=Perfect Patio
Size=97.570.383
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task35]
;SP03
Name=Cool Kitchen
Size=152.259.652
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task36]
;SP04
Name=Spooky
Size=173.514.726
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task37]
;SP05
Name=Movie Hangout
Size=230.032.281
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task38]
;SP06
Name=Romantic Garden
Size=215.182.158
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task39]
;SP07
Name=Kids Room
Size=161.518.991
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task40]
;SP08
Name=Backyard
Size=181.140.609
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task41]
;SP09
Name=Vintage Glamour
Size=174.919.641
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task42]
;SP10
Name=Bowling Night
Size=202.210.426
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task43]
;SP11
Name=Fitness
Size=163.485.752
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task44]
;SP12
Name=Toddler
Size=166.515.968
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task45]
;SP13
Name=Laundry Day
Size=161.686.806
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task46]
;SP14
Name=My First Pet
Size=171.336.762
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task47]
;SP15
Name=Moschino
Size=137.253.704
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task48]
;SP16
Name=Tiny Living
Size=223.848.296
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task49]
;SP17
Name=Nifty Knitting
Size=263.390.269
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task50]
;SP18
Name=Paranormal
Size=244.100.255
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

;;--------------------------------------------------------------
[Task51]
Name=Kits
Size=0
ShowInstallLabel=0
Checked=1
Enabled=1
Level=0

[Task52]
;SP20
Name=Throwback Fit Kit
Size=57.919.135
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task53]
;SP21
Name=Country Kitchen Kit
Size=56.417.783
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task54]
;SP22
Name=Bust the Dust Kit
Size=74.774.650
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task55]
;SP23
Name=Courtyard Oasis
Size=65.803.112
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task56]
;SP24
Name=Fashion Street Kit
Size=68.348.665
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task57]
;SP25
Name=Industrial Loft
Size=46.405.870
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task58]
;SP26
Name=Incheon Arrivals Kit
Size=73.997.467
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task59]
;SP28
Name=Modern Menswear Kit
Size=49.240.003
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task60]
;SP29
Name=Blooming Rooms Kit
Size=44.198.316
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task61]
;SP30
Name=Carnaval Streetwear Kit
Size=56.842.881
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task62]
;SP31
Name=Décor to the Max Kit
Size=35.343.063
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task63]
;SP32
Name=Moonlight Chic Kit
Size=84.299.598
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task64]
;SP33
Name=Little Campers Kit
Size=55.026.229
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task65]
;SP34
Name=First Fits Kit
Size=50.184.444
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task66]
;SP35
Name=Desert Luxe Kit
Size=49.300.586
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task67]
;SP36
Name=Pastel Pop Kit
Size=35.785.237
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task68]
;SP37
Name=Everyday Clutter Kit
Size=8.662.289
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task69]
;SP38
Name=Simtimates Collection Kit
Size=64.875.807
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task70]
;SP39
Name=Bathroom Clutter Kit
Size=11.505.842
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task71]
;SP40
Name=Greenhouse Haven Kit
Size=22.633.661
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task72]
;SP41
Name=Basement Treasures Kit
Size=22.746.991
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task73]
;SP42
Name=Grunge Revival Kit
Size=70.711.879
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task74]
;SP43
Name=Book Nook Kit
Size=21.277.557
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task75]
;SP44
Name=Poolside Splash Kit
Size=49.915.265
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task76]
;SP45
Name=Modern Luxe Kit
Size=22.870.084
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task77]
;SP46
Name=Home Chef Hustle Stuff Pack
Size=264.578.595
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task78]
;SP47
Name=Castle Estate Kit
Size=114.994.409
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

[Task79]
;SP48
Name=Goth Galore Kit
Size=59.628.888
ShowInstallLabel=0
Checked=1
Enabled=1
Level=1

;;--------------------------------------------------------------
[LauncherSettings]
InstallRedist=1

[Launch1]
Name=Visual C++ 2010
Exe1={app}\__Installer\vc\vc2010sp1\redist\vcredist_x86.exe
Exe2={app}\__Installer\vc\vc2010sp1\redist\vcredist_x64.exe
Argument=/q /norestart
BeforeInstall=0
Checked=1

[Launch2]
Name=Visual C++ 2013
Exe1={app}\__Installer\vc\vc2013\redist\vcredist_x86.exe
Exe2={app}\__Installer\vc\vc2013\redist\vcredist_x64.exe
Argument=/q /norestart
BeforeInstall=0
Checked=1

[Launch3]
Name=Visual C++ 2015
Exe1={app}\__Installer\vc\vc2015\redist\vc_redist.x86.exe
Exe2={app}\__Installer\vc\vc2015\redist\vc_redist.x64.exe
Argument=/q /norestart
BeforeInstall=0
Checked=1

[Launch4]
Name=Visual C++ 2019
Exe1={app}\__Installer\vc\vc2019\redist\vc_redist.x86.exe
Exe2={app}\__Installer\vc\vc2019\redist\vc_redist.x64.exe
Argument=/q /norestart
BeforeInstall=0
Checked=1