--cache=0

[Compression Methods]
Mask1=srep_new+7z/$bpkpack=bpk/$mp3pack=mpz_mtx/$mscpack=srep_new:m3f+MSC

;Final Compressors
FA-STORE=0
FA-MIN=1
FA-LOW=rep:1kb:256+exe+4x4:tor:1kb:h4kb
FA-FAST=rep:1kb+exe+delta+4x4:lzma:32kb:fast:32:mc4
FA-NORMAL=rep:1kb+exe+delta+4x4:lzma:32kb:normal:16:mc8
FA-HIGH=rep:1kb+exe+delta+4x4:lzma:32kb:normal:32:mc32
FA-BEST=exe+delta+lzma:32kb:normal:bt4:128
FA-MAX=rep:1kb+exe+delta+lzma:64m:ultra:bt4:128
FA-ULTRA=rep:1kb+exe+delta+lzma:128m:ultra:bt4:128

FA-BEST_SP=9x
FA-MAX_SP=x
FA-ULTRA_SP=x

0=storing
;1=rep:96m:256:c256+4x4:tor:3:8mb
2=rep:1kb:256+exe+4x4:tor:1kb:h4kb
3=rep:1kb+exe+delta+4x4:lzma:32kb:fast:32:mc4
4=rep:1kb+exe+delta+4x4:lzma:32kb:normal:16:mc8
5=rep:1kb+exe+delta+4x4:lzma:32kb:normal:32:mc32

LZMA    = lzma:a1:mfbt4:256m:fb273:mc1000000000:lc8
LZMA-MT = 4x4:b64mb:lzma:ultra:64m:bt4:fb273:lc8:mc1000000
LZMA2   = lzma2:d96m:fb273:lc4:mc1000000

; LOLZ_FAST   = lolz:d32m:mtt1:mt<thread>:fba4096:mc2
; LOLZ_NORMAL = lolz:d64m:mtt1:mt<thread>:mc1023
; LOLZ_HIGH   = lolz:dtb1:d128m:mtt1:mt<thread>:mc1023
; LOLZ_ULTRA  = lolz:dtb1:d256m:mtt1:mt<thread>:mc1023

LOLZ_FAST   = lolz:d<expr:((0.25*freememory/11)-(32*1048576*2))/min(thread,16)/1048576>:mtt1:mt<expr:min(thread,16)>:fba4096:mc2
LOLZ_NORMAL = lolz:d<expr:((0.45*freememory/11)-(32*1048576*2))/min(thread,16)/1048576>:mtt1:mt<expr:min(thread,16)>:mc1023
LOLZ_HIGH   = lolz:dtb1:d<expr:((0.65*freememory/11)-(32*1048576*2))/min(thread,16)/1048576>:mtt1:mt<expr:min(thread,16)>:mc1023
LOLZ_ULTRA  = lolz:dtb1:d<expr:((0.85*freememory/11)-(32*1048576*2))/min(thread,16)/1048576>:mtt1:mt<expr:min(thread,16)>:mc1023

DLolz = lolz
FLolz = LOLZ_FAST
NLolz = LOLZ_NORMAL
XLolz = LOLZ_HIGH
GLolz = LOLZ_ULTRA

xZST = zstd:19:-ultra:T0

;Pre-Compressors
PJ = precomp:t-j
UR = uelr:uv

;XTool
xZ1 = xt_zlib
xZ2 = xt_lz4
xZ3 = xt_lzo
xZ4 = xt_zstd
xZ5 = xt_oodle
xZ6 = xt_crilayla

xzlib = xt_zlib
xlz4 = xt_lz4
xlzo = xt_lzo
xzstd = xt_zstd
xoodle = xt_oodle
xcrilayla= xt_crilayla

;Media Lossless Compression
BPK = bpk
OGG = oggre
MSC = msc_tak:mp3=1:wav=1:raw=1:ddsraw=1:bmf=9:TAK=9:bmp=1:lzma,bt4,fb128,lc8
MSC_TAK  = msc_tak:mp3=1:wav=1:raw=1:ddsraw=1:bmf=9:TAK=9:bmp=1:lzma,bt4,fb128,lc8
MSC_FROG = msc_frog:mp3=1:wav=1:raw=1:ddsraw=1:bmf=9:TAK=9:bmp=1:lzma,bt4,fb128,lc8

;Razor Tools Predefined
MEXODUS = vfxrec
FIFA19  = cdt+fifa19_oo2reck
SR3REM  = vpprec
DSTRAN  = dst+dst_oo2reck

TEXT = dict+lzp
afr  = afr_019
msc  = msc_tak
srep = srep_new
SREP = srep_new:m3f:a16:d1g:1

; Expression example: <expr:0.75*memory/thread/1048576>
; 0.75       = percentage of calcule (75%)
; memory     = full system memory (RAM)
; freememory = free system memory (RAM)
; thread     = number of logical cores
; core       = number of physical cores
; 1048576    = convert result in bytes to mb

;========================================================================================
; PRECOMPRESSORS
;========================================================================================

[External compressor:afr_019]
header    = 0
packcmd   = "PRE\AFR\019\AFR.exe" e {options} $$arcdatafile$$.tmp $$arcpackedfile$$.tmp
unpackcmd = "PRE\AFR\019\AFR.exe" d #in #out <stdin> <stdout>

[External compressor:afr_020]
header    = 0
packcmd   = "PRE\AFR\020\AFR.exe" e {options} $$arcdatafile$$.tmp $$arcpackedfile$$.tmp
unpackcmd = "PRE\AFR\020\AFR.exe" d #in #out <stdin> <stdout>

[External compressor:xt_zlib]
header    = 0
packcmd   = "PRE\XTool\XTool.exe" e:precomp:t75p,c128m:zlib - - <stdin> <stdout>
unpackcmd = "PRE\XTool\XTool.exe" d:precomp:t100p - - <stdin> <stdout>

[External compressor:xt_lz4]
header    = 0
packcmd   = "PRE\XTool\XTool.exe" e:precomp:t100p,c128m:lz4 - - <stdin> <stdout>
unpackcmd = "PRE\XTool\XTool.exe" d:precomp:t100p - - <stdin> <stdout>

[External compressor:xt_lzo]
header    = 0
packcmd   = "PRE\XTool\XTool.exe" e:precomp:t100p,c128m:lzo - - <stdin> <stdout>
unpackcmd = "PRE\XTool\XTool.exe" d:precomp:t100p - - <stdin> <stdout>

[External compressor:xt_zstd]
header    = 0
packcmd   = "PRE\XTool\XTool.exe" e:precomp:t100p,c128m:zstd - - <stdin> <stdout>
unpackcmd = "PRE\XTool\XTool.exe" d:precomp:t100p - - <stdin> <stdout>

[External compressor:xt_oodle]
header    = 0
packcmd   = "PRE\XTool\XTool.exe" e:precomp:t100p:oodle - - <stdin> <stdout>
unpackcmd = "PRE\XTool\XTool.exe" d:precomp:t100p - - <stdin> <stdout>
datafile  = InFile

[External compressor:xt_crilayla]
header    = 0
packcmd   = "PRE\CriLayla\XTool.exe" e:precomp:t100p,c128m,v:crilayla - - <stdin> <stdout>
unpackcmd = "PRE\CriLayla\XTool.exe" d:precomp:t100p - - <stdin> <stdout>

[External compressor:xtool]
header    = 0
default   = -c64mb -t100p
packcmd   = "PRE\XTool_2020\XTool.exe" precomp { -option} - - <stdin> <stdout>
unpackcmd = "PRE\XTool_2020\XTool.exe" decode { -option} -t100p - - <stdin> <stdout>

[External compressor:precomp]
header    = 0
packcmd   = "PRE\PRECOMP\precomp.exe" -cn -intense0 -o$$arcpackedfile$$.tmp $$arcdatafile$$.tmp
unpackcmd = "PRE\PRECOMP\precomp.exe" -r -o$$arcdatafile$$.tmp $$arcpackedfile$$.tmp

[External compressor:uelr]
header     = 0
default    = ulv
packcmd    = "PRE\UELR\uelr.exe" {option} InFile OutFile
unpackcmd  = "FAZip32.exe" -i0 decompress:uelr_d <stdin> <stdout>
datafile   = InFile
packedfile = OutFile

[External compressor:oo2reck,oo2recm,oo2recs]
header    = 0
packcmd   = "PRE\OodleRec\{compressor}\{compressor}.exe" e <stdin> <stdout>
unpackcmd = "PRE\OodleRec\{compressor}\{compressor}.exe" d <stdin> <stdout>

[External compressor:zstdrec]
header    = 0
packcmd   = "PRE\RZTools\ZSTDRec\zstdrec.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\ZSTDRec\zstdrec.exe" d <stdin> <stdout>

[External compressor:lzorec]
header    = 0
packcmd   = "PRE\RZTools\LZORec\lzorec.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\LZORec\lzorec.exe" d <stdin> <stdout>

[External compressor:lzxrec]
header    = 0
packcmd   = "PRE\RZTools\LZXRec\lzxrec.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\LZXRec\lzxrec.exe" d <stdin> <stdout>

; Metro Exodus
[External compressor:vfxrec]
header    = 0
packcmd   = "PRE\RZTools\MetroExodus\vfxrec.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\MetroExodus\vfxrec.exe" d <stdin> <stdout>

;FIFA 19
[External compressor:fifa19_oo2reck]
header    = 0
packcmd   = "PRE\RZTools\FIFA19\fifa19_oo2reck.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\FIFA19\fifa19_oo2reck.exe" d <stdin> <stdout>

[External compressor:cdt]
header    = 0
packcmd   = "PRE\RZTools\FIFA19\cdt.exe" <stdin> <stdout>
unpackcmd = "PRE\RZTools\FIFA19\cdt.exe" <stdin> <stdout>

;Saints Row 3 Remaster
[External compressor:vpprec]
header    = 0
packcmd   = "PRE\RZTools\SR3Remaster\vpprec.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\SR3Remaster\vpprec.exe" d <stdin> <stdout>

;Death Stranding
[External compressor:dst_oo2reck]
header    = 0
packcmd   = "PRE\RZTools\DStranding\oo2reck.exe" e <stdin> <stdout>
unpackcmd = "PRE\RZTools\DStranding\oo2reck.exe" d <stdin> <stdout>

[External compressor:dst]
header    = 0
packcmd   = "PRE\RZTools\DStranding\dstool.exe" <stdin> <stdout>
unpackcmd = "PRE\RZTools\DStranding\dstool.exe" <stdin> <stdout>

;Unreal Engine 4 Decryption Tool
[External compressor:ue4dt]
header    = 0
packcmd   = "PRE\RZTools\UE4DT\ue4dt.exe" e {options} <stdin> <stdout>
unpackcmd = "PRE\RZTools\UE4DT\ue4dt.exe" d {options} <stdin> <stdout>

;The Elder Scrolls V: Skyrim
[External compressor:xtool_skyrim]
header    = 0
packcmd   = "PRE\RZTools\XToolSkyrim\XTool.exe" precomp -mskyrim -c32mb -t100p --dbase - - <stdin> <stdout>
unpackcmd = "PRE\RZTools\XToolSkyrim\XTool.exe" decode -t100p - - <stdin> <stdout>

;========================================================================================
; MEDIA COMPRESSORS
;========================================================================================

[External compressor:7zdll]
header     = 0
default    = -m0=rep1 -m1=mp3det -m2=packmp3d:mt14:c16m -m3=lzma2
packcmd    = "MEDIA\7ZDLL\7z.exe" a -tpa -mcrc=0 -mx=0 -bb0 -mf=off {options} -si <stdin> FileOut.pa
unpackcmd  = "MEDIA\7ZDLL\7z.exe" x -mmt=on -so FileOut.pa <stdout>
packedfile = FileOut.pa

[External compressor:7zdll-pm]
header     = 0
default    = -m0=rep1 -m1=mp3det -m2=packmp3d:mt14:c16m -m3=lzma2
packcmd    = "MEDIA\7ZDLL\7z.exe" a -tpa -mcrc=0 -mx=0 -bb0 -mf=off { -option}:mt14:c16m -si <stdin> FileOut.pa
unpackcmd  = "MEDIA\7ZDLL\7z.exe" x -mmt=on -so FileOut.pa <stdout>
packedfile = FileOut.pa

[External compressor:7zdll-ns]
; solid = 0 for brunsli and lepton
header     = 0
default    = -m0=rep1 -m1=brunsli -m2=lzma2
packcmd    = "MEDIA\7ZDLL\7z.exe" a -tpa -mcrc=0 -mx=0 -bb0 -mf=off {options} -si <stdin> FileOut.pa
unpackcmd  = "MEDIA\7ZDLL\7z.exe" x -mmt=on -so FileOut.pa <stdout>
packedfile = FileOut.pa
solid      = 0

[External compressor:bpk]
;Cls library in Setup.dll
header     = 0
packcmd    = "FAZip32.exe" -i0 compress:bpk_c <stdin> <stdout>
unpackcmd  = "FAZip32.exe" -i0 decompress:bpk_d <stdin> <stdout>
datafile   = InFile
packedfile = OutFile

[External compressor:msc_tak,msc_frog]
;Cls library in Setup.dll
header     = 0
default    = -raw=1 -bmf=9 -bmp=1 -wav=1 -mp3=1
packcmd    = "MEDIA\MSC\MSC.exe" c -f -v {options} InFile OutFile
unpackcmd  = "FAZip32.exe" -i0 decompress:msc_d <stdin> <stdout>
datafile   = InFile
packedfile = OutFile

[External compressor:brunsli]
header     = 0
packcmd    = "MEDIA\BRUNSLI\brunsli.exe" c $$arcdatafile$$.jpg $$arcdatafile$$.brn
unpackcmd  = "MEDIA\BRUNSLI\brunsli.exe" d $$arcdatafile$$.brn $$arcdatafile$$.jpg
datafile   = $$arcdatafile$$.jpg
packedfile = $$arcdatafile$$.brn
solid      = 0

[External compressor:packjpg]
header     = 0
packcmd    = "MEDIA\JPG\packjpg.exe" -np {options} $$arcdatafile$$.jpg
unpackcmd  = "MEDIA\JPG\packjpg.exe" -np {options} $$arcdatafile$$.pjg
datafile   = $$arcdatafile$$.jpg
packedfile = $$arcdatafile$$.pjg
solid      = 0

[External compressor:packmp3]
header     = 0
packcmd    = "MEDIA\MP3\packmp3.exe" -np {options} $$arcdatafile$$.mp3
unpackcmd  = "MEDIA\MP3\packmp3.exe" -np {options} $$arcdatafile$$.pmp
datafile   = $$arcdatafile$$.mp3
packedfile = $$arcdatafile$$.pmp
solid      = 0

[External compressor:oggre]
;Cls library in Setup.dll
header     = 0
packcmd    = "MEDIA\OGGRE\OGGRE_enc.exe" {options} InFile OutFile
unpackcmd  = "FAZip32.exe" -i0 decompress:oggre_d <stdin> <stdout>
datafile   = InFile
packedfile = OutFile

[External compressor:mpz,mpzapi]
header    = 0
packcmd   = "MEDIA\MPZ\mpzapi.exe" c <stdin> <stdout>
unpackcmd = "MEDIA\MPZ\mpzapi.exe" d <stdin> <stdout>

;========================================================================================

[External compressor:srep_old,srep_new]
;Cls library in Setup.dll
header     = 0
default    = -m3f -a0/0
packcmd    = "OTHERS\SREP\srep.exe" -hash- {options} InFile OutFile
unpackcmd  = "FAZip32.exe" -i0 decompress:srep_d <stdin> <stdout>
datafile   = InFile
packedfile = OutFile

;========================================================================================
; FINAL COMPRESSORS
;========================================================================================

[External compressor:lzma_sdk]
header    = 0
packcmd   = "FINAL\7ZIP\lzma_sdk.exe" e -a1 -si -so -mt12 <stdin> <stdout> 
unpackcmd = "FINAL\7ZIP\lzma_sdk.exe" d -si -so <stdin> <stdout>

[External compressor:rep,mm,exe,exe2,4x4,dict,lzp,tta,delta,lzma]
header    = 0
packcmd   = "FAZip.exe" -i0   compress:{compressor}{:option} <stdin> <stdout>
unpackcmd = "FAZip.exe" -i0 decompress:{compressor}{:option} <stdin> <stdout>

[External compressor:lzma2,7z]
header    = 0
;default   = :d25:fb=273:mf=bt4:mc=1000000:lc=4:lp=0
default   = :d192m:fb=273:mc=1000000:lc=4:lp=0
packcmd   = "FINAL\7ZIP\7z.exe" a -txz -an -mcrc=0 -m1=lzma2{:option}:mf=bt4 -mmt=on -mx9 -si -so <stdin> <stdout>
unpackcmd = "FINAL\7ZIP\7z.exe" x -txz -mmt2 -an -y -si -so <stdin> <stdout>

[External compressor:bcm]
header    = 0
default   =-b64m -x-
packcmd   = "FINAL\BCM\bcm.exe" -c {options} $$arcdatafile$$.tmp <stdout>
unpackcmd = "FINAL\BCM\bcm.exe" -d -c <stdin> <stdout>

[External compressor:rar]
cmem      = 200
dmem      = 200
default   = 5
packcmd   = "FINAL\RAR\rar.exe" a -m{option} -mdg -s -mt4 $$arcpackedfile$$.tmp.rar $$arcdatafile$$.tmp
unpackcmd = "FINAL\RAR\rar.exe" e -mt4 $$arcpackedfile$$.tmp.rar
datafile   = $$arcdatafile$$.tmp
packedfile = $$arcpackedfile$$.tmp.rar

[External compressor:zstd]
header    = 0
;Maximum: -22 --ultra -T2
default   = -19 -T0
packcmd   = "FINAL\ZSTD\zstd.exe" {options} <stdin> <stdout>
unpackcmd = "FINAL\ZSTD\zstd.exe" -d -f <stdin> <stdout>

[External compressor:kraken,mermaid,selkie,leviathan]
header    = 0
default   = -c64mb -t100p 
packcmd   = "FINAL\OO2MTC\oo2mtc.exe" {compressor} { -option} <stdin> <stdout>
unpackcmd = "FINAL\OO2MTC\oo2mtc.exe" d <stdin> <stdout>

[External compressor:lolz]
header     = 0
packcmd    = "FINAL\LOLZ\lolz.exe" {options} InFile OutFile
unpackcmd  = "FAZip32.exe" -i0 decompress:lolz_d <stdin> <stdout>
datafile   = InFile
packedfile = OutFile

[External compressor:rz,razor]
;razor standard
header    = 0
packcmd   = "FINAL\RAZOR\STANDARD\RZ.exe" a -d 64m $$arcpackedfile$$.tmp $$arcdatafile$$.tmp
unpackcmd = "FINAL\RAZOR\STANDARD\RZ.exe" e -y $$arcpackedfile$$.tmp $$arcdatafile$$.tmp

[External compressor:rz_stdio,razor_stdio]
;razor stdio patch
header    = 0
default   = 256m
packcmd   = "FINAL\RAZOR\STDIO\RAZOR.exe" a -y -d {option} $stdio$ <stdin> <stdout>
unpackcmd = "FINAL\RAZOR\STDIO\RAZOR.exe" e -y $stdio$ <stdin> <stdout>

;========================================================================================
; PMT SETTINGS
;========================================================================================

[External compressor:mpz_pmt,mpzapi_pmt,precomp_pmt,razor_pmt,rz_pmt]
header    = 0
packcmd   = "OTHERS\PMT\PMT.exe" e {compressor} -b128m -t100p - - <stdin> <stdout>
unpackcmd = "OTHERS\PMT\PMT.exe" d {compressor} -t100p - - <stdin> <stdout>

;========================================================================================
; MTX SETTINGS
;========================================================================================

[External compressor:precomp_mtx]
header    = 0
default   = -c256m -t100p
packcmd   = "OTHERS\MTX\MTX64.exe" a -mprecomp {options} --basePath=".\..\..\" --cfgFile="$basePath$\DSG_Arc.ini" - - <stdin> <stdout>
unpackcmd = "OTHERS\MTX\MTX64.exe" x -mprecomp {options} --basePath=".\..\..\" --cfgFile="$basePath$\DSG_Arc.ini" - - <stdin> <stdout>

[External compressor:mpz_mtx,mpzapi_mtx]
header    = 0
default   = -c64m -t100p
packcmd   = "OTHERS\MTX\MTX64.exe" a -mmpz {options} --basePath=".\..\..\" --cfgFile="$basePath$\DSG_Arc.ini" - - <stdin> <stdout>
unpackcmd = "OTHERS\MTX\MTX64.exe" x -mmpz {options} --basePath=".\..\..\" --cfgFile="$basePath$\DSG_Arc.ini" - - <stdin> <stdout>

[External compressor:rz_mtx,razor_mtx]
header    = 0
default   = -c64m -t100p
packcmd   = "OTHERS\MTX\MTX64.exe" a -mrz {options} --basePath=".\..\..\" --cfgFile="$basePath$\DSG_Arc.ini" - - <stdin> <stdout>
unpackcmd = "OTHERS\MTX\MTX64.exe" x -mrz {options} --basePath=".\..\..\" --cfgFile="$basePath$\DSG_Arc.ini" - - <stdin> <stdout>

;========================================================================================
