;;**************************************************************************************************
;;**************************************************************************************************
[XTool_Bms2xtl_L0] //item listed in download database file
; { Ni No Kuni 2 }
;XTool_Bms2xtl_DB;     Type: RADIO; Text: Ni No Kuni 2;                                             Method: xtool;   Param: c32mb:mnnk2;                  Check: FileExists|TOOLS\Bms2XTool\Plugins\nnnk2.7z;                        URL: (Bms2 Plugin)|?4ypRavQrcYRWZkH04v0dGCytLL_sNBDt|TOOLS\Bms2XTool\Plugins\nnnk2.7z;

[XTool_Bms2xtl_L1] //item listed in create database file
; { Ni No Kuni 2 }
XTool_Bms2xtl_DB;     Type: RADIO; Text: Ni No Kuni 2;                                             Method: xtool;   Param: c32mb:mnnk2;

;;**************************************************************************************************
;;**************************************************************************************************
[COPY.BEFORE] //.DB = create database file //.DL = download database file
; { Ni No Kuni 2 }
NiNoKuni2.DL;                Method: xtool:mnnk2:0;
NiNoKuni2.DB;                Method: xtool:mnnk2:1;

;;**************************************************************************************************
[Function.XTOOL_SETTINGS]
INI: {Param1|PRE\XTool_2020\XTool.ini}; Action: WRITE; Section: {Param2|cpk}; Key: Encode; Value: {Param3|crilayla.exe d <library>};
INI: {Param1|PRE\XTool_2020\XTool.ini}; Action: WRITE; Section: {Param2|cpk}; Key: Decode; Value: {Param4|crilayla.exe e <library>};

[Copy.XTool_Crilayla_EXTERNAL]
TOOLS\Crilayla\crilayla.exe;                                                                  Destination: PRE\XTool_2020\crilayla.exe;
TOOLS\Crilayla\crilayla.dll;                                                                  Destination: PRE\XTool_2020\crilayla.dll;
TOOLS\Crilayla\XTool.ini;                                                                     Destination: PRE\XTool_2020\XTool.ini;
PSC: Function.XTOOL_SETTINGS|PRE\XTool_2020\XTool.ini|cpk|crilayla.exe d <library>|crilayla.exe e <library>;

[Copy.NiNoKuni2.DB]
PSC: Copy.XTool_Crilayla_EXTERNAL;
CMD: (copy /Y "!ArcPath!\TOOLS\Bms2XTool\bms2xtl_default.ini" "!ArcPath!\TOOLS\Bms2XTool\bms2xtl.ini" >nul); Silent: yes;
DWL: TOOLS\Bms2XTool\Scripts\cpk.bms;                                                         URL: 1erCkaJ5WigLfQ0t7Bq6iLw-g9enDNNTH;      Description: Quick BMS Script;
CMD: (cd /D "!ArcPath!\TOOLS\Bms2XTool")&(call "!ArcPath!\TOOLS\Bms2XTool\bms2xtl.exe" "!ArcPath!\TOOLS\Bms2XTool\Scripts\cpk.bms" "!GamePath!\*.cpk" "!ArcPath!\PRE\XTool_2020\nnk2.xtl"); Destination: !ArcPath!\PRE\XTool_2020\nnk2.xtl; Database: yes;

[Copy.NiNoKuni2.DL]
PSC: Copy.XTool_Crilayla_EXTERNAL;
TOOLS\Bms2XTool\Plugins\mnnk2.7z|mnnk2.xtl;                                                   Destination: PRE\XTool_2020\mnnk2.xtl;

;;**************************************************************************************************
;;**************************************************************************************************
[DECOMPRESSORS] //create file list to setup dll decompressors
; { Ni No Kuni 2 }
NiNoKuni2;                   Method: xtool:mnnk2;

;;**************************************************************************************************
[Decomp.NiNoKuni2]
TOOLS\Crilayla\crilayla.exe;                                                                  Destination: XTool_2020\crilayla.exe;
TOOLS\Crilayla\crilayla.dll;                                                                  Destination: XTool_2020\crilayla.dll;
TOOLS\Crilayla\XTool.ini;                                                                     Destination: XTool_2020\XTool.ini;
PSC: Function.XTOOL_SETTINGS|XTool_2020\XTool.ini|cpk|crilayla.exe d <library>|crilayla.exe e <library>;

;;**************************************************************************************************
;;**************************************************************************************************
[DOWNLOAD] //download compressors before compression
; { need to download QuickBMS executable file }
1PI-2VzMJ_uomOQZYml4jqHZn00W5ibas|TOOLS\Bms2XTool\*.*;  Method: xtool:mnnk2:1;   Check: FileExists|TOOLS\Bms2XTool\quickbms_4gb_files.exe;  Description: QuickBMS executable file;
;;**************************************************************************************************
; { Ni No Kuni 2 - download .xtl plugin }
?ZmKdpP6R0FCCv9sLDYQUcxtlqHXqTJhR|TOOLS\Bms2XTool\Plugins\nnk2.7z;             Method: xtool:mnnk2:0;        Check: FileExists|TOOLS\Bms2XTool\Plugins\nnk2.7z;          Description: Ni No Kuni 2 (XTool Bms2 Plugin);
