[SREP]
Bufsize=24m
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
Memory=50%-512m
TempPath=.\

[SREP_OLD]
Bufsize=24m
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
Memory=50%-512m
TempPath=.\

[SREP_NEW]
Bufsize=24m
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
Memory=50%-512m
TempPath=.\

[Precomp]
Memory=128
TempPath=.\

[LOLZ]
Bufsize=512k
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
MaxThreadsUsage=50%
MaxMemoryUsage=100%
ldmfTempPath=.\
ldmfMaxMemoryUsage=512m
ldmfDeleteTmp=0

[AFR]
Threads=Auto

[AFR_019]
Threads=Auto

[UELR]
; Bufsize=16m
ReadBufSize=2048k
WriteBufSize=4096k

[MPZMT]
MaxThreads=8
Exe=.\MPZ\mpzapi.exe
Temp=.\