[SREP]
Bufsize=24m
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
Memory=20%
TempPath=.\

[SREP_OLD]
Bufsize=24m
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
Memory=20%
TempPath=.\

[SREP_NEW]
Bufsize=24m
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
Memory=20%
TempPath=.\

[Precomp]
Memory=128
TempPath=.\

[LOLZ]
Bufsize=512k
transfer_ReadBufSize=512k
transfer_WriteBufSize=512k
MaxThreadsUsage=25%
MaxMemoryUsage=25%
ldmfTempPath=.\
ldmfMaxMemoryUsage=64m
ldmfDeleteTmp=0

[AFR]
Threads=2

[AFR_019]
Threads=2

[UELR]
; Bufsize=16m
ReadBufSize=1024k
WriteBufSize=2048k

[MPZMT]
MaxThreads=2
Exe=.\MPZ\mpzapi.exe
Temp=.\