[Settings]
Name=Project Demigod
APPID=
Buildversion=13333238
Size=6.02 GB
REPACKER=DeliciousMeatPop
Creator=ARMGDDN Games
DefaultInstallDir={sd}\Games
UnInstallFolder=_UnInstall
ShowLanguageBox=1
CompactMode=0
RunAppAsAdmin=0
[Executable1] 
ShortcutName=Project Demigod
Exe=Project Demigod.exe
ExeParam=
IconFileName={app}\icon.ico
IconIndex=0 
Flags=
;Component= 

[InfoBefore]
//----------------------------------------------- Setup\InfoBefore.rtf \ InfoBefore.txt
Enable=0

[Skin]
//----------------------------------------------- Setup\Filename.cjstyles \ Filename.vsf
EnableCjstyles=0
CjstylesFile=Concave.cjstyles
CjstylesParam=

EnableVCL=1
VCLFile=BlueGraphite.vsf

[Background]
//----------------------------------------------- Setup\Background\#.jpg
Enable=1
BackgroundDuration=5000
BackgroundAnimation=1
BGAfterInstall=1

[Batch]
Enable=0
BatchFile=removeVR.bat

//CUSTOMIZE ABOVE THIS LINE
[Music]
//----------------------------------------------- Setup\Filename.mp3
Enable=1
MusicFile=Music.mp3
MusicVolume=70

[Text]
WelcomeLabel1Top=235
WelcomeLabel2Top=295
FinishLabel1Top=235
FinishLabel2Top=295
WelcomeLabel1FontSize=14
WelcomeLabel2FontSize=10
FinishLabel1FontSize=14
FinishLabel2FontSize=10
Font=Alegreya Sans
FontColor=$ffffff

[Button]
PlaySound=1

[ComponentsSettings]
Enable=0
FlatPageMode=0
ShowComponentSize=1

;; requires at least two components to enable page. 
;; if components is used the global size will be ignored. 
Component1.Name=Component 1
Component1.ItemType=CHECK
Component1.Size=4.15 GB
Component1.Level=0
Component1.Checked=1
Component1.Enabled=1

Component2.Name=Component 2
Component2.ItemType=CHECK
Component2.Size=8.75 GB
Component2.Level=0
Component2.Checked=1
Component2.Enabled=1

Component3.Name=Component 3
Component3.ItemType=CHECK
Component3.Size=18.00 GB
Component3.Level=0
Component3.Checked=1
Component3.Enabled=1

Component4.Name=Component 4
Component4.ItemType=CHECK
Component4.Size=18.00 GB
Component4.Level=0
Component4.Checked=1
Component4.Enabled=1

[Website]
Enable=1
WebsiteButtonText=AG Telegram
URL=https://t.me/ARMGDDNGames

[Splash]
//----------------------------------------------- Setup\Filename.png
Enable=1
SplashFile=Splash.png
SplashFadeIn=1500
SplashShow=3000
SplashFadeOut=1500

[Redists]
Enable=0

Redist1.Enable=1
Redist1.Name=DirectX
Redist1.Level=0
Redist1.ItemType=CHECK
Redist1.Checked=1
Redist1.Enabled=1
Redist1.Exe32={src}\DirectX\dxsetup.exe
Redist1.Exe64={src}\DirectX\dxsetup.exe
Redist1.Param=

Redist2.Enable=1
Redist2.Name=VC
Redist2.Level=0
Redist2.ItemType=CHECK
Redist2.Checked=1
Redist2.Enabled=1
Redist2.Exe32={src}\vc_redist.x64.exe
Redist2.Exe64={src}\vc_redist.x64.exe
Redist2.Param=
//////////////////////////////////////////////////////////////////////