; ===================================================================

[External compressor:precomp]
header    = 0
unpackcmd = "Precomp\precomp.exe" -o$$arcdatafile$$.tmp -r $$arcpackedfile$$.tmp

; ===================================================================

[External compressor:xt_zlib,xt_lz4,xt_lzo,xt_zstd,xt_oodle]
header    = 0
unpackcmd = "XTool\XTool.exe" d:precomp:t90p - - <stdin> <stdout>

[External compressor:xt_crilayla]
header    = 0
unpackcmd = "CriLayla\XTool.exe" d:precomp:t50p - - <stdin> <stdout>

; ===================================================================

[External compressor:xtool]
header    = 0
unpackcmd = "XTool_2020\XTool.exe" decode { -option} -t100p - - <stdin> <stdout>

; ===================================================================

;The Elder Scrolls V: Skyrim
[External compressor:xtool_skyrim]
header    = 0
unpackcmd = "XToolSkyrim\XTool.exe" decode -t100p - - <stdin> <stdout>

; ===================================================================

[External compressor:packjpg]
header     = 0
unpackcmd  = "JPG\packjpg.exe" -np {options} $$arcdatafile$$.pjg
datafile   = $$arcdatafile$$.jpg
packedfile = $$arcdatafile$$.pjg
solid      = 0

[External compressor:packmp3]
header     = 0
unpackcmd  = "MP3\packmp3.exe" -np {options} $$arcdatafile$$.pmp
datafile   = $$arcdatafile$$.mp3
packedfile = $$arcdatafile$$.pmp
solid      = 0

[External compressor:mpz,mpzapi]
header    = 0
unpackcmd = "MPZ\mpzapi.exe" d <stdin> <stdout>

; ===================================================================

[External compressor:lzma_sdk]
header    = 0
unpackcmd = "7ZIP\lzma_sdk.exe" d -si -so <stdin> <stdout>

[External compressor:lzma2,7z]
header    = 0
unpackcmd = "7ZIP\7z.exe" x -txz -an -y -si -so <stdin> <stdout>

[External compressor:rar]
dmem       = 200
unpackcmd  = "RAR\UnRAR.exe" e -mt4 $$arcpackedfile$$.tmp.rar
datafile   = $$arcdatafile$$.tmp
packedfile = $$arcpackedfile$$.tmp.rar

[External compressor:zstd]
header     = 0
unpackcmd  = "ZSTD\zstd.exe" -d {options} -f <stdin> <stdout>

; ===================================================================

[External compressor:mpz_pmt,mpzapi_pmt,precomp_pmt]
header    = 0
unpackcmd = "PMT\PMT.exe" d {compressor} -t100p - - <stdin> <stdout>

; ===================================================================

[External compressor:precomp_mtx]
header    = 0
default   = -t100p
unpackcmd = "MTX\MTX64.exe" x -mprecomp {options} --basePath=".\..\" --cfgFile="$basePath$\Arc.ini" - - <stdin> <stdout>

[External compressor:mpz_mtx,mpzapi_mtx]
header    = 0
default   = -t100p
unpackcmd = "MTX\MTX64.exe" x -mmpz {options} --basePath=".\..\" --cfgFile="$basePath$\Arc.ini" - - <stdin> <stdout>

; ===================================================================
