[Config]
SafeMode=0
UserInput=
Exclude=lzma_dynamic,snappy
lz4=lz4hc
gzip=zlib
deflate=zlib
zlib_noerror=zlib
deflate_noerror=zlib
oodle=leviathan
XMemDecompress=xmemcompress

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;Origins, Odyssey, Valhalla
;oodle=mermaid

;Shadow of War
;oodle=kraken

;FF7
;UserInput=0x23989837645C9D28BA58072B2076E895B853A7C9E1C5591B814C4FD2A2D7B782
;oodle=kraken

;Horizon Zero Dawn
;oodle=kraken

;Jedi Fallen Order
;oodle=mermaid
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
